config/routes.rb
require 'api_constraints'

Iscore::Application.routes.draw do

  resources :service_types

  resources :organizations

  resources :availability_service_checks

  resources :availability_checks

  resources :usability_reports_checks

  resources :usability_reports_submissions

  resources :usability_reports

  resources :services

  resources :anomalies

  resources :flags

  get "home/index"

  get "home/about"

  get "dashboard/index"

  get "dashboard/blue"

  get "dashboard/green"

  get "dashboard/red"

  get "dashboard/white"

  get "sessions/new"

  resources :sites

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  match '/sign_in', to: 'sessions#new'
  match 'sign_out', to: 'sessions#destroy'
  root to: "home#index"
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :sites
    end
  end

end

app/models/anomaly.rb
# == Schema Information
#
# Table name: anomalies
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  due_time    :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Anomaly < ActiveRecord::Base
  attr_accessible :description, :due_time, :name
end

app/controllers/anomalies_controller.rb
class AnomaliesController < ApplicationController
  # GET /anomalies
  # GET /anomalies.json
  def index
    @anomalies = Anomaly.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @anomalies }
    end
  end

  # GET /anomalies/1
  # GET /anomalies/1.json
  def show
    @anomaly = Anomaly.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @anomaly }
    end
  end

  # GET /anomalies/new
  # GET /anomalies/new.json
  def new
    @anomaly = Anomaly.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @anomaly }
    end
  end

  # GET /anomalies/1/edit
  def edit
    @anomaly = Anomaly.find(params[:id])
  end

  # POST /anomalies
  # POST /anomalies.json
  def create
    @anomaly = Anomaly.new(params[:anomaly])

    respond_to do |format|
      if @anomaly.save
        format.html { redirect_to @anomaly, notice: 'Anomaly was successfully created.' }
        format.json { render json: @anomaly, status: :created, location: @anomaly }
      else
        format.html { render action: "new" }
        format.json { render json: @anomaly.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /anomalies/1
  # PUT /anomalies/1.json
  def update
    @anomaly = Anomaly.find(params[:id])

    respond_to do |format|
      if @anomaly.update_attributes(params[:anomaly])
        format.html { redirect_to @anomaly, notice: 'Anomaly was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @anomaly.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anomalies/1
  # DELETE /anomalies/1.json
  def destroy
    @anomaly = Anomaly.find(params[:id])
    @anomaly.destroy

    respond_to do |format|
      format.html { redirect_to anomalies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/anomalies_helper.rb
module AnomaliesHelper
end

app/views/anomalies/_form.html.erb
<%= simple_form_for(@anomaly) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :due_time %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/anomalies/edit.html.erb
<% provide(:title, 'Editing Anomaly') %>
<h1>Editing Anomaly</h1>

<%= render 'form' %>

<%= link_to 'Show', @anomaly %> |
<%= link_to 'Back', anomalies_path %>

app/views/anomalies/index.html.erb
<h1>Listing anomalies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Due time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @anomalies.each do |anomaly| %>
  <tr>
    <td><%= anomaly.name %></td>
    <td><%= anomaly.description %></td>
    <td><%= anomaly.due_time %></td>
    <td><%= link_to 'Show', anomaly %></td>
    <td><%= link_to 'Edit', edit_anomaly_path(anomaly) %></td>
    <td><%= link_to 'Destroy', anomaly, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Anomaly', new_anomaly_path %>

app/views/anomalies/new.html.erb
<h1>New anomaly</h1>

<%= render 'form' %>

<%= link_to 'Back', anomalies_path %>

app/views/anomalies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @anomaly.name %>
</p>

<p>
  <b>Description:</b>
  <%= @anomaly.description %>
</p>

<p>
  <b>Due time:</b>
  <%= @anomaly.due_time %>
</p>


<%= link_to 'Edit', edit_anomaly_path(@anomaly) %> |
<%= link_to 'Back', anomalies_path %>