config/routes.rb
require 'api_constraints'

Iscore::Application.routes.draw do

  resources :service_types

  resources :organizations

  resources :availability_service_checks

  resources :availability_checks

  resources :usability_reports_checks

  resources :usability_reports_submissions

  resources :usability_reports

  resources :services

  resources :anomalies

  resources :flags

  get "home/index"

  get "home/about"

  get "dashboard/index"

  get "dashboard/blue"

  get "dashboard/green"

  get "dashboard/red"

  get "dashboard/white"

  get "sessions/new"

  resources :sites

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  match '/sign_in', to: 'sessions#new'
  match 'sign_out', to: 'sessions#destroy'
  root to: "home#index"
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :sites
    end
  end

end

app/models/usability_reports_check.rb
# == Schema Information
#
# Table name: usability_reports_checks
#
#  id                              :integer          not null, primary key
#  work                            :boolean
#  site_id                         :integer
#  service_id                      :integer
#  use                             :string(255)
#  usability_reports_submission_id :integer
#  created_at                      :datetime         not null
#  updated_at                      :datetime         not null
#

class UsabilityReportsCheck < ActiveRecord::Base
  belongs_to :site
  belongs_to :service
  has_many :usability_reports_submission
  attr_accessible :use, :work
end

app/controllers/usability_reports_checks_controller.rb
class UsabilityReportsChecksController < ApplicationController
  # GET /usability_reports_checks
  # GET /usability_reports_checks.json
  def index
    @usability_reports_checks = UsabilityReportsCheck.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @usability_reports_checks }
    end
  end

  # GET /usability_reports_checks/1
  # GET /usability_reports_checks/1.json
  def show
    @usability_reports_check = UsabilityReportsCheck.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @usability_reports_check }
    end
  end

  # GET /usability_reports_checks/new
  # GET /usability_reports_checks/new.json
  def new
    @usability_reports_check = UsabilityReportsCheck.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @usability_reports_check }
    end
  end

  # GET /usability_reports_checks/1/edit
  def edit
    @usability_reports_check = UsabilityReportsCheck.find(params[:id])
  end

  # POST /usability_reports_checks
  # POST /usability_reports_checks.json
  def create
    @usability_reports_check = UsabilityReportsCheck.new(params[:usability_reports_check])

    respond_to do |format|
      if @usability_reports_check.save
        format.html { redirect_to @usability_reports_check, notice: 'Usability reports check was successfully created.' }
        format.json { render json: @usability_reports_check, status: :created, location: @usability_reports_check }
      else
        format.html { render action: "new" }
        format.json { render json: @usability_reports_check.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /usability_reports_checks/1
  # PUT /usability_reports_checks/1.json
  def update
    @usability_reports_check = UsabilityReportsCheck.find(params[:id])

    respond_to do |format|
      if @usability_reports_check.update_attributes(params[:usability_reports_check])
        format.html { redirect_to @usability_reports_check, notice: 'Usability reports check was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @usability_reports_check.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usability_reports_checks/1
  # DELETE /usability_reports_checks/1.json
  def destroy
    @usability_reports_check = UsabilityReportsCheck.find(params[:id])
    @usability_reports_check.destroy

    respond_to do |format|
      format.html { redirect_to usability_reports_checks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/usability_reports_checks_helper.rb
module UsabilityReportsChecksHelper
end

app/views/usability_reports_checks/_form.html.erb
<%= simple_form_for(@usability_reports_check) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <%= f.input :work %>

    <%= f.association :site %>

    <%= f.association :service %>

    <%= f.input :use %>

    <%= f.association :usability_reports_submission %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/usability_reports_checks/edit.html.erb
<h1>Editing usability_reports_check</h1>

<%= render 'form' %>

<%= link_to 'Show', @usability_reports_check %> |
<%= link_to 'Back', usability_reports_checks_path %>

app/views/usability_reports_checks/index.html.erb
<h1>Listing usability_reports_checks</h1>

<table>
  <tr>
    <th>Work</th>
    <th>Site</th>
    <th>Service</th>
    <th>Use</th>
    <th>Usability reports submission</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @usability_reports_checks.each do |usability_reports_check| %>
  <tr>
    <td><%= usability_reports_check.work %></td>
    <td><%= usability_reports_check.site %></td>
    <td><%= usability_reports_check.service %></td>
    <td><%= usability_reports_check.use %></td>
    <td><%= usability_reports_check.usability_reports_submission %></td>
    <td><%= link_to 'Show', usability_reports_check %></td>
    <td><%= link_to 'Edit', edit_usability_reports_check_path(usability_reports_check) %></td>
    <td><%= link_to 'Destroy', usability_reports_check, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Usability reports check', new_usability_reports_check_path %>

app/views/usability_reports_checks/new.html.erb
<h1>New usability_reports_check</h1>

<%= render 'form' %>

<%= link_to 'Back', usability_reports_checks_path %>

app/views/usability_reports_checks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Work:</b>
  <%= @usability_reports_check.work %>
</p>

<p>
  <b>Site:</b>
  <%= @usability_reports_check.site %>
</p>

<p>
  <b>Service:</b>
  <%= @usability_reports_check.service %>
</p>

<p>
  <b>Use:</b>
  <%= @usability_reports_check.use %>
</p>

<p>
  <b>Usability reports submission:</b>
  <%= @usability_reports_check.usability_reports_submission %>
</p>


<%= link_to 'Edit', edit_usability_reports_check_path(@usability_reports_check) %> |
<%= link_to 'Back', usability_reports_checks_path %>