config/routes.rb
require 'api_constraints'

Iscore::Application.routes.draw do

  resources :service_types

  resources :organizations

  resources :availability_service_checks

  resources :availability_checks

  resources :usability_reports_checks

  resources :usability_reports_submissions

  resources :usability_reports

  resources :services

  resources :anomalies

  resources :flags

  get "home/index"

  get "home/about"

  get "dashboard/index"

  get "dashboard/blue"

  get "dashboard/green"

  get "dashboard/red"

  get "dashboard/white"

  get "sessions/new"

  resources :sites

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  match '/sign_in', to: 'sessions#new'
  match 'sign_out', to: 'sessions#destroy'
  root to: "home#index"
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :sites
    end
  end

end

app/controllers/service_types_controller.rb
class ServiceTypesController < ApplicationController
  # GET /service_types
  # GET /service_types.json
  def index
    @service_types = ServiceType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @service_types }
    end
  end

  # GET /service_types/1
  # GET /service_types/1.json
  def show
    @service_type = ServiceType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @service_type }
    end
  end

  # GET /service_types/new
  # GET /service_types/new.json
  def new
    @service_type = ServiceType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @service_type }
    end
  end

  # GET /service_types/1/edit
  def edit
    @service_type = ServiceType.find(params[:id])
  end

  # POST /service_types
  # POST /service_types.json
  def create
    @service_type = ServiceType.new(params[:service_type])

    respond_to do |format|
      if @service_type.save
        format.html { redirect_to @service_type, notice: 'Service type was successfully created.' }
        format.json { render json: @service_type, status: :created, location: @service_type }
      else
        format.html { render action: "new" }
        format.json { render json: @service_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /service_types/1
  # PUT /service_types/1.json
  def update
    @service_type = ServiceType.find(params[:id])

    respond_to do |format|
      if @service_type.update_attributes(params[:service_type])
        format.html { redirect_to @service_type, notice: 'Service type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @service_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_types/1
  # DELETE /service_types/1.json
  def destroy
    @service_type = ServiceType.find(params[:id])
    @service_type.destroy

    respond_to do |format|
      format.html { redirect_to service_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/service_types_helper.rb
module ServiceTypesHelper
end

app/views/service_types/_form.html.erb
<%= simple_form_for(@service_type) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <%= f.input :name %>

    <%= f.input :port %>

    <%= f.input :description %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/service_types/edit.html.erb
<h1>Editing service_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @service_type %> |
<%= link_to 'Back', service_types_path %>

app/views/service_types/index.html.erb
<h1>Listing service_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Port</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @service_types.each do |service_type| %>
  <tr>
    <td><%= service_type.name %></td>
    <td><%= service_type.port %></td>
    <td><%= service_type.description %></td>
    <td><%= link_to 'Show', service_type %></td>
    <td><%= link_to 'Edit', edit_service_type_path(service_type) %></td>
    <td><%= link_to 'Destroy', service_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Service type', new_service_type_path %>

app/views/service_types/new.html.erb
<h1>New service_type</h1>

<%= render 'form' %>

<%= link_to 'Back', service_types_path %>

app/views/service_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @service_type.name %>
</p>

<p>
  <b>Port:</b>
  <%= @service_type.port %>
</p>

<p>
  <b>Description:</b>
  <%= @service_type.description %>
</p>


<%= link_to 'Edit', edit_service_type_path(@service_type) %> |
<%= link_to 'Back', service_types_path %>